version: '2'

services:
  go-server:
    image: gocd/gocd-server:16.12.0
    volumes:
      - ./opt/server/var/lib/go-server:/var/lib/go-server
      - ./opt/server/var/log/go-server:/var/log/go-server
      - ./opt/server/etc/go:/etc/go
    ports:
      - 8153:8153
      - 8154:8154
    environment:
      - AGENT_KEY=${GOAGENT_KEY}

  go-agent:
    image: gocd/gocd-agent:16.12.0
    volumes:
      - ./opt/agent/go-agent:/etc/default/go-agent
    environment:
      - GO_SERVER_URL=http://go-server:8154/go
      - AGENT_KEY=${GOAGENT_KEY}
    depends_on:
      - go-server
      - haproxy

  haproxy:
    build:
      context: .
      dockerfile: opt/haproxy/Dockerfile
    volumes:
      - ./opt/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./opt/haproxy/haproxy.pem:/etc/ssl/private/haproxy.pem
    depends_on:
      - go-server
